### ISSUE TITLE
Inventory save

### ISSUE THREAD

**Issue by m7md1112** [ayunami2000/eaglercraft-replit#3]
Hi um how do I save all my items in my inventory when I close my private server I am having a issue with that, if anyone can help? I'm using Replit.

**Comment by ayunami2000** [comment]
Run /save-all in console to save manually

**Comment by m7md1112** [comment]
it didnt work.
and how do i become a admin i want to be creative but it asks for permission

**Comment by Coder002-239** [comment]
> Run /save-all in console to save manually

but you can run save-on to save it automatically, right?

**Comment by ayunami2000** [comment]
It should but I can't guarantee it works
